title: CCIE Security v6.1 Study Notes
description: CCIE Security v6.1 Blueprint に基づく学習サイト


remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true
nav_enabled: true
